# Specify the parent image from which we build
FROM ubuntu

# Set the working directory
WORKDIR /app

APT_DEPENDENCIES

PYTHON_DEPENDENCIES

# Run the application
CMD ["/app/hello_zed_src/build/ZED_Tutorial_1"]
